/**
 * Generated by `createschema resident.Resident 'user:Relationship:User:CASCADE; organization:Relationship:Organization:PROTECT; property:Relationship:Property:PROTECT; billingAccount?:Relationship:BillingAccount:SET_NULL; unitName:Text;'`
 */
const get = require('lodash/get')

const { isSoftDelete } = require('@open-condo/keystone/access')
const { throwAuthenticationError } = require('@open-condo/keystone/apolloErrorFormatter')
const { getById } = require('@open-condo/keystone/schema')

const {
    checkPermissionsInEmployedOrganizations,
    getEmployedOrRelatedOrganizationsByPermissions,
} = require('@condo/domains/organization/utils/accessSchema')
const { RESIDENT, SERVICE } = require('@condo/domains/user/constants/common')
const { canDirectlyManageSchemaObjects, canDirectlyReadSchemaObjects } = require('@condo/domains/user/utils/directAccess')

async function canReadResidents ({ authentication: { item: user }, context, listKey }) {
    if (!user) return throwAuthenticationError()
    if (user.deletedAt) return false

    if (user.isAdmin || user.isSupport) return {}

    const directAccess = await canDirectlyReadSchemaObjects(user, listKey)
    if (directAccess) return {}

    if (user.type === RESIDENT) {
        return { user: { id: user.id } }
    }

    if (user.type === SERVICE) return false

    const organizationIds = await getEmployedOrRelatedOrganizationsByPermissions(context, user, 'canReadResidents')

    return {
        organization: {
            id_in: organizationIds,
        },
    }
}

async function canManageResidents ({ authentication: { item: user }, originalInput, operation, itemId, context, listKey }) {
    if (!user) return throwAuthenticationError()
    if (user.deletedAt) return false
    if (user.isAdmin || user.isSupport) return true

    const hasDirectAccess = await canDirectlyManageSchemaObjects(user, listKey, originalInput, operation)
    if (hasDirectAccess) return true

    if (user.type === RESIDENT) {
        // Only soft-delete is allowed for current resident
        if (operation === 'update' && itemId) {
            const resident = await getById('Resident', itemId)
            if (!resident || resident.user !== user.id) return false
            if (isSoftDelete(originalInput)) return true
        }

        return false
    }

    if (user.type === SERVICE) return false

    let organizationId

    if (operation === 'create') {
        organizationId = get(originalInput, ['organization', 'connect', 'id'])
    } else if (operation === 'update' && itemId) {
        const item = await getById('Resident', itemId)
        organizationId = get(item, 'organization')
    }

    if (!organizationId) return false

    return await checkPermissionsInEmployedOrganizations(context, user, [organizationId], 'canManageResidents')
}

/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canReadResidents,
    canManageResidents,
}